pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git "https://github.com/eaneto/lab-eng-soft-p2.git"
            }
        }
        stage('Build') {
            dir("example-app") {
                steps {
                    go build
                }
            }
        }
    }
}
