- name: Jenkins configuration
  hosts: jenkins
  become: true
  vars:
    jenkins_version: "2.277.4"
    jenkins_install_via: "apt"
    jenkins_home: /home/jenkins/data
    jenkins_java_opts: "-Djenkins.install.runSetupWizard=false -Xmx4096m"
    jenkins_custom_plugins:
      # Dependências base
      - "strict-crumb-issuer.jpi"
      - "trilead-api.jpi"
      - "caffeine-api.jpi"
      - "script-security.jpi"
      - "jaxb.jpi"
      - "structs.jpi"
      - "command-launcher.jpi"
      - "bouncycastle-api.jpi"
      - "jdk-tool.jpi"
      # Credentials
      - "credentials.jpi"
      # SSH Credentials
      - "ssh-credentials.jpi"
      # SCM Api
      - "scm-api.jpi"
      # Git client
      - "jsch.jpi"
      - "git-client.jpi"
      # Git
      - "mailer.jpi"
      - "workflow-step-api.jpi"
      - "workflow-scm-step.jpi"
      - "git.jpi"
      # Workflow Aggregator/Pipeline
      - "workflow-api.jpi"
      - "workflow-support.jpi"
      - "plugin-util-api.jpi"
      - "font-awesome-api.jpi"
      - "jquery3-api.jpi"
      - "popper-api.jpi"
      - "bootstrap4-api.jpi"
      - "display-url-api.jpi"
      - "checks-api.jpi"
      - "snakeyaml-api.jpi"
      - "jackson2-api.jpi"
      - "echarts-api.jpi"
      - "junit.jpi"
      - "matrix-project.jpi"
      - "lockable-resources.jpi"
      - "workflow-job.jpi"
      - "ace-editor.jpi"
      - "workflow-cps.jpi"
      - "pipeline-input-step.jpi"
      - "pipeline-graph-analysis.jpi"
      - "pipeline-stage-step.jpi"
      - "pipeline-rest-api.jpi"
      - "handlebars.jpi"
      - "momentjs.jpi"
      - "pipeline-stage-view.jpi"
      - "durable-task.jpi"
      - "workflow-durable-task-step.jpi"
      - "apache-httpcomponents-client-4-api.jpi"
      - "workflow-basic-steps.jpi"
      - "cloudbees-folder.jpi"
      - "git-server.jpi"
      - "workflow-cps-global-lib.jpi"
      - "branch-api.jpi"
      - "workflow-multibranch.jpi"
      - "pipeline-build-step.jpi"
      - "pipeline-milestone-step.jpi"
      - "plain-credentials.jpi"
      - "credentials-binding.jpi"
      - "pipeline-model-api.jpi"
      - "pipeline-model-extensions.jpi"
      - "pipeline-stage-tags-metadata.jpi"
      - "pipeline-model-definition.jpi"
      - "workflow-aggregator.jpi"
    jenkins_jobs:
      - "NotifyCI"
    jenkins_apt_packages:
      - openjdk-11-jdk
      - git
      - build-essential
    jenkins_java_version: "java-1.11.0-openjdk-amd64"
    jenkins_config_owner: "jenkins"
    jenkins_config_group: "jenkins"
  roles:
    - emmetog.jenkins
  tasks:
    - name: Download golang
      get_url:
        url: https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
        dest: /tmp
    - name: Extract go tar
      shell:
        cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.16.4.linux-amd64.tar.gz
    - name: Add golang bin directory to path
      shell:
        cmd: cp /usr/local/go/bin/go /usr/local/bin/go
