- name: Jenkins configuration
  hosts: jenkins
  become: true
  vars:
    jenkins_version: "2.277.4"
    jenkins_install_via: "apt"
    jenkins_home: /tmp/jenkins
    jenkins_jobs:
      - "notify-ci"
    jenkins_plugins:
      - ssh-credentials
      - credentials
      - scm-api
      - git
      - git-client
      - greenballs
      - ws-cleanup
      - pipeline
    jenkins_apt_packages:
      - openjdk-11-jdk
    jenkins_java_version: "java-1.11.0-openjdk-amd64"
  roles:
    - emmetog.jenkins
  tasks:
    - name: Download golang
      get_url:
        url: https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
        dest: /tmp
    - name: Extract go tar
      shell:
        cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.16.4.linux-amd64.tar.gz
    - name: Add golang bin directory to path
      shell:
        cmd: echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin"' >> /etc/environment
