- name: Jenkins configuration
  hosts: jenkins
  become: true
  vars:
    jenkins_version: "2.277.4"
    jenkins_install_via: "apt"
    jenkins_home: /home/jenkins/data
    jenkins_custom_plugins:
      - "strict-crumb-issuer.jpi"
      - "trilead-api.hpi"
      - "credentials.hpi"
      - "ssh-credentials.hpi"
      - "scm-api.hpi"
      - "ws-cleanup.hpi"
      - "git-client.hpi"
      - "git.hpi"
      - "workflow-aggregator.hpi" # Pipeline plugin
    jenkins_apt_packages:
      - openjdk-11-jdk
    jenkins_java_version: "java-1.11.0-openjdk-amd64"
    jenkins_config_owner: "jenkins"
    jenkins_config_group: "jenkins"
  roles:
    - emmetog.jenkins
  tasks:
    - name: Instala o git
      apt:
        name: git
        state: present # estado present quer dizer que é pra instalar o pacote
        update_cache: yes # Roda apt update antes da instalação
    - name: Instala o make
      apt:
        name: build-essential
        state: present # estado present quer dizer que é pra instalar o pacote
        update_cache: yes # Roda apt update antes da instalação
    - name: Download golang
      get_url:
        url: https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
        dest: /tmp
    - name: Extract go tar
      shell:
        cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.16.4.linux-amd64.tar.gz
    - name: Add golang bin directory to path
      shell:
        cmd: cp /usr/local/go/bin/go /usr/local/bin/go
