- name: Configuração do servidor de monitoração
  hosts: monitor # Aplica apenas no host monitor
  become: true # Roda como root
  tasks:
    - name: Instala o Nagios
      apt:
        name: nagios3
        state: present # estado present quer dizer que é pra instalar o pacote
        update_cache: yes # Roda apt update antes da instalação
    - name: Cria usuário do nagiosadmin no nagios3
      shell:
        # Cria o usuário admin com a senha admin
        cmd: htpasswd -b -c /etc/nagios3/htpasswd.users nagiosadmin admin
    - name: Copia configuração do monitor local para a VM
      copy:
        src: monitor.cfg
        dest: /etc/nagios3/conf.d/monitor.cfg
    - name: Realiza o reload no serviço no nagios3
      # Recarrega o serviço do nagios3 para utilizar as novas configurações
      service:
        name: nagios3
        state: reloaded
